apiVersion: apps/v1
kind: Deployment 
metadata: 
  name: {{ .Release.Name }}-deployment
  labels: 
    app: {{ .Values.appLabel }}
spec: 
  replicas: {{ .Values.replicaCount }}
  selector: 
    matchLabels: 
      app: {{ .Values.appLabel }}
    template: 
      metadata: 
        labels: 
          app: {{ .Values.appLabel}}
      spec: 
        containers: 
         - name: zomato-container 
           image: "{{ .Values.image.repository}}:{{ .Values.image.tag}}"
           imagePullPolicy: {{ .Values.pullPolicy}}
           ports: 
              - containerPort: {{ .Values.containerport }}

